### ISSUE TITLE
an object

### ISSUE THREAD

**Issue by borisorlov21** [Godiesc/floorp-one#11]
your topic is great, I did it differently
![Screenshot from 2024-05-05 12-53-11](https://github.com/Godiesc/floorp-one/assets/66428911/7283af74-20f7-4242-b2f4-74cc0007db6d)

**Comment by Godiesc** [comment]
hi,
I don't know what you mean, I see in your screenshot you don't have active a compatible theme and the style made space for the left-sidebar but you don't have it on...
