### ISSUE TITLE
Websites have a strange color

### ISSUE THREAD

**Issue by Car0lina5** [Godiesc/floorp-one#3]
I noticed that websites have a strange color in the background, even though dark mode is turned off. I discovered that the problem is in the "one_left-sidebar.css" file, delete the:
body {
         background-color: var(--lwt-frame) !important;
     }
which is located on line 316. This caused the color to go out and the sites to go back to normal. The problem is that I have no idea what this does and I would like to know if I will have any problems removing this part. Thank you.

![image](https://github.com/Godiesc/floorp-one/assets/117472773/4cd2db29-41e4-4bfb-9e42-e986f05ddbcb)
![image](https://github.com/Godiesc/floorp-one/assets/117472773/33cbff7c-5142-4e8e-8327-a52e4eb63c06)

**Comment by Godiesc** [comment]
hi, I thinks I did that code to test and forgot to delete, or maybe is a code to set the color outside of the rounded zone of the web content. I will check it, thanks for the report.

**Comment by Godiesc** [comment]
I can say I don't have that problem with the background of the webpages, I tested in the sites you shared. Share with me maybe other config you have active?

![imagen](https://github.com/Godiesc/floorp-one/assets/22057609/344db958-d4b7-4385-942b-d24995eecd31)

![imagen](https://github.com/Godiesc/floorp-one/assets/22057609/ac78824e-a7ea-41c5-972c-a2c152da4ebb)

**Comment by Car0lina5** [comment]
Hello, I discovered the mistake I made. I placed the files inside the CSS folder that Floorp creates. When placed directly in the chrome folder everything is fine. I never do this, I don't even know why I put it in the CSS folder. Anyway, stupid of me haha.
