### ISSUE TITLE
Varios bugs

### ISSUE THREAD

**Issue by SantiGLI** [Godiesc/floorp-one#5]
Soy usuario de Firefox original pero quería probar Floorp. Lo primero que hice fue instalarle Floorp One pero me encontré con muchos bugs.
Primero: Tengo la sidebar en la derecha aunque no haya activado la sidebar en la derecha.
Segundo: Mis marcadores en vez de estar en la sidebar, están como los predeterminados, arriba.
Tercero: Al lado de la sidebar en la derecha, tengo una franja violeta que recorta el espacio de visión del navegador.
Cuarto: Arriba a la izquierda está el logo de Floorp y un poco de espacio abajo, como si fuera el principio de la sidebar que quedó atrás de la página en la que esté.
Quinto: Cuando activé "floorpone.selected-tab-gradient-border" los bordes de las pestañas se desaparecieron.

Adjunto la captura de pantalla: 
![image](https://github.com/Godiesc/floorp-one/assets/110741430/18722ac0-be7f-45be-af9c-85ba9d653d35)

Floorp 11.8.2 ● Firefox 115.7.0 ● Windows 11 23H2 (22631.3085)

**Comment by Godiesc** [comment]
hi, don't forget to restart the browser to see the changes take effect.
1.- La posición de la sidebar la puedes cambiar desde about:preferences:

![imagen](https://github.com/Godiesc/floorp-one/assets/22057609/cd77cee6-6991-48a2-9a82-97fd4d89142f)

2.- Floorp tiene una barra lateral extra por defecto y este theme css usa esa para darle estilo así que ya no se usa la barra de marcadores para ese propósito, tu barra de marcadores conserva su posición y función.

3.- Si no activaste esta preferencia en about:config `floorpone.sidebar-on-right` the first solution will solve it.

4.- I hope the first solution will solve it.

5.- I tested just now and seems right:

![imagen](https://github.com/Godiesc/floorp-one/assets/22057609/066bc842-251a-4d70-9fa7-289f5d446cc2)
