### ISSUE TITLE
Sidebar issue on latest floorp version 

### ISSUE THREAD

**Issue by CyrilTheLearner** [Godiesc/floorp-one#8]
![issue](https://github.com/Godiesc/floorp-one/assets/110766220/e9f92cd6-2693-42b5-82a2-e4ad9552726b)
 a random space appears

**Comment by Godiesc** [comment]
hi,
maybe you are experiment the same issue from this user: https://github.com/Godiesc/floorp-one/issues/2 , he changed a preference in about:config page and the issue appeared.

**Comment by CyrilTheLearner** [comment]
Okay I solved it, basically sidebar experiment was enabled when I disabled the issue is gone , thx for ur attention:))
